apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistem-meetings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sistem-meetings
  template:
    metadata:
      labels:
        app: sistem-meetings
    spec:
      containers:
        - image: zdays/sistem-meetings:latest
          name: sistem-meetings
          imagePullPolicy: "Always"
          env:
            - name: SISTEM_MEETINGS_PORT
              value: "8080"
            - name: SISTEM_MEETINGS_DATABASE_HOST
              value: dumbo.db.elephantsql.com
            - name: SISTEM_MEETINGS_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: elephantdb
                  key: name
            - name: SISTEM_MEETINGS_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: elephantdb
                  key: username
            - name: SISTEM_MEETINGS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elephantdb
                  key: password
            - name: SISTEM_PROJECTS_MICROSERVICE_URL
              value: http://sistem-projects:8080/api/v1
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sistem-meetings
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: sistem-meetings
